// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz0DnpNSygfXvoQj_uv_mUYVEVeIZKN3s',
    appId: '1:230624874365:web:09584752b7458ba2e24614',
    messagingSenderId: '230624874365',
    projectId: 'skillory-3407f',
    authDomain: 'skillory-3407f.firebaseapp.com',
    storageBucket: 'skillory-3407f.firebasestorage.app',
    measurementId: 'G-JD6BZTWCVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAii7lQNwSuofscZTdSyPMJRHOagQzq8k0',
    appId: '1:230624874365:android:5c049b8af4dcc041e24614',
    messagingSenderId: '230624874365',
    projectId: 'skillory-3407f',
    storageBucket: 'skillory-3407f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC764ZFC40eJrFPR4O_BA8M0DGGLfZJWr8',
    appId: '1:230624874365:ios:c2af08b862da5331e24614',
    messagingSenderId: '230624874365',
    projectId: 'skillory-3407f',
    storageBucket: 'skillory-3407f.firebasestorage.app',
    iosBundleId: 'com.example.skilloryCoet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC764ZFC40eJrFPR4O_BA8M0DGGLfZJWr8',
    appId: '1:230624874365:ios:c2af08b862da5331e24614',
    messagingSenderId: '230624874365',
    projectId: 'skillory-3407f',
    storageBucket: 'skillory-3407f.firebasestorage.app',
    iosBundleId: 'com.example.skilloryCoet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz0DnpNSygfXvoQj_uv_mUYVEVeIZKN3s',
    appId: '1:230624874365:web:050c72874ae7195fe24614',
    messagingSenderId: '230624874365',
    projectId: 'skillory-3407f',
    authDomain: 'skillory-3407f.firebaseapp.com',
    storageBucket: 'skillory-3407f.firebasestorage.app',
    measurementId: 'G-WC7EQ8ZVRM',
  );
}
